language: python

matrix:
  include:

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6.1

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7.12

    - os: linux
      python: 2.7

    - os: linux
      python: 3.6

cache:
  directories:
    - $HOME/.pyenv/versions/3.6.1
    - $HOME/.pyenv/versions/3.5.2
    - $HOME/.pyenv/versions/3.4.5
    - $HOME/.pyenv/versions/3.3.6
    - $HOME/.pyenv/versions/2.7.12
    - $HOME/downloads

before_install:
  - python --version
  - pip --version
  - cd miniupnpc
  - pip install scikit-ci==0.13.0 scikit-ci-addons==0.11.0
  - ci_addons --install ../addons

install:
  - ci install
