language: python

matrix:
  include:

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6.1

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7.12

    - os: linux
      python: 2.7

    - os: linux
      python: 3.6

before_install:
  - python --version
  - pip --version
  - cd miniupnpc
  - pip install scikit-ci==0.13.0 scikit-ci-addons==0.11.0
  - ci_addons --install ../addons

install:
  - ci install

script:
  - ci test
