language: python

matrix:
  include:

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6.1

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7.12

    - os: linux
      python: 2.7

    - os: linux
      python: 3.6

before_install:
  - cd miniupnpc
  - pip install -U pip
  - pip install -r requirements.txt

script: python setup.py bdist_wheel
